const laptops = [
    // {
    //     nombre:'Laptop DELL Inspiron 15 3525 Ryzen 5 5500U 16GB 1.2TB SSD 15.6" D6DM6-V2 Dell 3515-V3',
    //     procesador: 'AMD Ryzen 5 5500U',
    //     grafica: 'AMD Radeon Vega 8',
    //     memoriaRam: '16GB',
    //     almacenamiento: '1TB SSD',
    //     bateria: 5000,
    //     interfaz: 'PCI-express',
    //     precio: 15000,
    //     imagen: '7fb81180-3575-424c-9cb2-c31e16241726.dd94e29875eb8a07469bc597540c48f4.jpg',
    //     oferta: false,
    //     descuento: 0,
    //     sistemaOperativoId: 3,
    //     marcasLaptopId: 2,
    //     tiendaId: 1
    // },
    // {
    //     nombre:'Laptop Gamer HP Victus 15-fb0122la AMD Ryzen 5 Nvidia GTX-1650 8GB RAM 512GB SSD',
    //     procesador: 'AMD Ryzen 5 5600H',
    //     grafica: 'Nvidia GTX 1650',
    //     memoriaRam: '8GB',
    //     almacenamiento: '512GB SSD',
    //     bateria: 5000,
    //     interfaz: 'PCI-express',
    //     precio: 15000,
    //     imagen: '00019749731906l.jpg',
    //     oferta: false,
    //     descuento: 0,
    //     sistemaOperativoId: 3,
    //     marcasLaptopId: 1,
    //     tiendaId: 2
    // },
    // {
    //     nombre:'Laptop HP 14-dq2531la Intel Core i3 16GB RAM 512GB SSD',
    //     procesador: 'Intel Core i3-1115G4',
    //     grafica: 'Intel Graphics',
    //     memoriaRam: '16GB',
    //     almacenamiento: '512GB SSD',
    //     bateria: 5000,
    //     interfaz: 'PCI-express',
    //     precio: 15000,
    //     imagen: '00019749716182l.jpg',
    //     oferta: false,
    //     descuento: 0,
    //     sistemaOperativoId: 3,
    //     marcasLaptopId: 1,
    //     tiendaId: 3
    // },
    // {
    //     nombre:'Laptop HP 15-fd0000la Intel Core i3 8 Núcleos 8GB RAM 512GB SSD Azul',
    //     procesador: 'Intel Core i3-N305',
    //     grafica: 'Intel Graphics',
    //     memoriaRam: '8GB',
    //     almacenamiento: '512GB SSD',
    //     bateria: 5000,
    //     interfaz: 'PCI-express',
    //     precio: 15000,
    //     imagen: '00019749716428l.jpg',
    //     oferta: false,
    //     descuento: 0,
    //     sistemaOperativoId: 3,
    //     marcasLaptopId: 1,
    //     tiendaId: 4
    // },
    // {
    //     nombre:'Laptop Gamer Asus ROG ZEPHYRUS Ryzen 7 GeForce RTX 3060 16GB 512GB SSD',
    //     procesador: 'AMD Ryzen 7 5800H',
    //     grafica: 'Nvidia RTX 3060',
    //     memoriaRam: '16GB',
    //     almacenamiento: '512GB SSD',
    //     bateria: 5000,
    //     interfaz: 'PCI-express',
    //     precio: 15000,
    //     imagen: '00075976321829l.jpg',
    //     oferta: false,
    //     descuento: 0,
    //     sistemaOperativoId: 3,
    //     marcasLaptopId: 4,
    //     tiendaId: 5
    // },
    // {
    //     nombre:'Laptop Gamer Dell Inspiron G15 5520 Intel Core i5 GeForce RTX 3050 8GB RAM 512GB SSD',
    //     procesador: 'Intel Core i5-12500H',
    //     grafica: 'Intel Graphics',
    //     memoriaRam: '8GB',
    //     almacenamiento: '512GB SSD',
    //     bateria: 5000,
    //     interfaz: 'PCI-express',
    //     precio: 15000,
    //     imagen: '50420fa8-1932-4a2e-bd9c-2e93ecfee4c7.a5b44cb5fd9cb9ec8c5d4af050fd4e78.jpg',
    //     oferta: false,
    //     descuento: 0,
    //     sistemaOperativoId: 3,
    //     marcasLaptopId: 2,
    //     tiendaId: 1
    // },
    // {
    //     nombre:'Laptop Dell Vostro 3400 14P Intel Core i3-1135G7 8GB RAM 1TB DD',
    //     procesador: 'Intel Core i3-1115G4',
    //     grafica: 'Intel UHD Graphics',
    //     memoriaRam: '8GB',
    //     almacenamiento: '1TB HDD',
    //     bateria: 5000,
    //     interfaz: 'PCI-express',
    //     precio: 10899,
    //     imagen: '00088411638515-1l.jpg',
    //     oferta: false,
    //     descuento: 0,
    //     sistemaOperativoId: 3,
    //     marcasLaptopId: 2,
    //     tiendaId: 2
    // },
    // {
    //     nombre:'Laptop Gaming Lenovo Legion 5 15IMH05H Intel Core i5 Gen 10th 8GB RAM 1TB DD más 128GB SSD',
    //     procesador: 'Intel Core i5-1035G4',
    //     grafica: 'Nvidia GTX 1660Ti',
    //     memoriaRam: '8GB',
    //     almacenamiento: '128GB SSD + 1TB HDD',
    //     bateria: 5000,
    //     interfaz: 'PCI-express',
    //     precio: 39586,
    //     imagen: '00019523508114l.jpg',
    //     oferta: false,
    //     descuento: 0,
    //     sistemaOperativoId: 3,
    //     marcasLaptopId: 6,
    //     tiendaId: 3
    // },
    // {
    //     nombre:'Laptop HP Pavilion 15-eg0513la Procesador Intel Core i5 8GB RAM, 512GB SSD',
    //     procesador: 'Intel Core i5-1035G4',
    //     grafica: 'Intel Iris Xe Graphics 80EU',
    //     memoriaRam: '8GB',
    //     almacenamiento: '512GB SSD',
    //     bateria: 5000,
    //     interfaz: 'PCI-express',
    //     precio: 16499,
    //     imagen: '00019749709804l.jpg',
    //     oferta: false,
    //     descuento: 0,
    //     sistemaOperativoId: 3,
    //     marcasLaptopId: 1,
    //     tiendaId: 4
    // },
    // {
    //     nombre:'Laptop HP 14-dq2531la Intel Core i3 16GB RAM 512GB SSD',
    //     procesador: 'Intel Core i3-1115G4',
    //     grafica: 'Intel Graphics',
    //     memoriaRam: '16GB',
    //     almacenamiento: '512GB SSD',
    //     bateria: 6000,
    //     interfaz: 'PCI-express',
    //     precio: 16499,
    //     imagen: '00019749716182l.jpg',
    //     oferta: false,
    //     descuento: 0,
    //     sistemaOperativoId: 3,
    //     marcasLaptopId: 1,
    //     tiendaId: 5
    // },
    // {
    //     nombre:'Laptop Dell Intel Core i5 5ta Generación 8gb Ram 240gb Disco Solido SSD HDMI WiFi Cámara Dell Latitude E5450',
    //     procesador: 'Intel Core i5-6200U',
    //     grafica: 'Intel Graphics',
    //     memoriaRam: '8GB',
    //     almacenamiento: '256GB SSD',
    //     bateria: 6000,
    //     interfaz: 'PCI-express',
    //     precio: 5400,
    //     imagen: '4617a6f5-7ebd-488c-9480-0eb51a70ef40.e73850c4f2b627f53ee5370c33ce7d3d.jpg',
    //     oferta: false,
    //     descuento: 0,
    //     sistemaOperativoId: 3,
    //     marcasLaptopId: 2,
    //     tiendaId: 1
    // }, 
    {
        "nombre": "Laptop DELL Inspiron 15 3525 Ryzen 5 5500U 16GB 1.2TB SSD 15.6\" D6DM6-V2 Dell 3515-V3",
        "procesador": "AMD Ryzen 5 5500U",
        "grafica": "AMD Radeon Vega 8",
        "memoriaRam": "16GB",
        "almacenamiento": "1TB SSD",
        "bateria": 5000,
        "interfaz": "PCI-express",
        "precio": 15000,
        "imagen": "7fb81180-3575-424c-9cb2-c31e16241726.dd94e29875eb8a07469bc597540c48f4.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 3,
        "marcasLaptopId": 2,
        "tiendaId": 1
      },
      {
        "nombre": "Laptop Gamer HP Victus 15-fb0122la AMD Ryzen 5 Nvidia GTX-1650 8GB RAM 512GB SSD",
        "procesador": "AMD Ryzen 5 5600H",
        "grafica": "Nvidia GTX 1650",
        "memoriaRam": "8GB",
        "almacenamiento": "512GB SSD",
        "bateria": 5000,
        "interfaz": "PCI-express",
        "precio": 15000,
        "imagen": "00019749731906l.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 3,
        "marcasLaptopId": 1,
        "tiendaId": 2
      },
      {
        "nombre": "Laptop HP 14-dq2531la Intel Core i3 16GB RAM 512GB SSD",
        "procesador": "Intel Core i3-1115G4",
        "grafica": "Intel Graphics",
        "memoriaRam": "16GB",
        "almacenamiento": "512GB SSD",
        "bateria": 5000,
        "interfaz": "PCI-express",
        "precio": 15000,
        "imagen": "00019749716182l.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 3,
        "marcasLaptopId": 1,
        "tiendaId": 3
      },
      {
        "nombre": "Laptop HP 15-fd0000la Intel Core i3 8 Núcleos 8GB RAM 512GB SSD Azul",
        "procesador": "Intel Core i3-N305",
        "grafica": "Intel Graphics",
        "memoriaRam": "8GB",
        "almacenamiento": "512GB SSD",
        "bateria": 5000,
        "interfaz": "PCI-express",
        "precio": 15000,
        "imagen": "00019749716428l.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 3,
        "marcasLaptopId": 1,
        "tiendaId": 4
      },
      {
        "nombre": "Laptop Gamer Asus ROG ZEPHYRUS Ryzen 7 GeForce RTX 3060 16GB 512GB SSD",
        "procesador": "AMD Ryzen 7 5800H",
        "grafica": "Nvidia RTX 3060",
        "memoriaRam": "16GB",
        "almacenamiento": "512GB SSD",
        "bateria": 5000,
        "interfaz": "PCI-express",
        "precio": 15000,
        "imagen": "00075976321829l.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 3,
        "marcasLaptopId": 4,
        "tiendaId": 5
      },
      {
        "nombre": "Laptop Gamer Dell Inspiron G15 5520 Intel Core i5 GeForce RTX 3050 8GB RAM 512GB SSD",
        "procesador": "Intel Core i5-12500H",
        "grafica": "Intel Graphics",
        "memoriaRam": "8GB",
        "almacenamiento": "512GB SSD",
        "bateria": 5000,
        "interfaz": "PCI-express",
        "precio": 15000,
        "imagen": "50420fa8-1932-4a2e-bd9c-2e93ecfee4c7.a5b44cb5fd9cb9ec8c5d4af050fd4e78.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 3,
        "marcasLaptopId": 2,
        "tiendaId": 1
      },
      {
        "nombre": "Laptop Dell Vostro 3400 14P Intel Core i3-1135G7 8GB RAM 1TB DD",
        "procesador": "Intel Core i3-1115G4",
        "grafica": "Intel UHD Graphics",
        "memoriaRam": "8GB",
        "almacenamiento": "1TB HDD",
        "bateria": 5000,
        "interfaz": "PCI-express",
        "precio": 10899,
        "imagen": "00088411638515-1l.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 3,
        "marcasLaptopId": 2,
        "tiendaId": 2
      },
      {
        "nombre": "Laptop Gaming Lenovo Legion 5 15IMH05H Intel Core i5 Gen 10th 8GB RAM 1TB DD más 128GB SSD",
        "procesador": "Intel Core i5-1035G4",
        "grafica": "Nvidia GTX 1660Ti",
        "memoriaRam": "8GB",
        "almacenamiento": "128GB SSD + 1TB HDD",
        "bateria": 5000,
        "interfaz": "PCI-express",
        "precio": 39586,
        "imagen": "00019523508114l.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 3,
        "marcasLaptopId": 6,
        "tiendaId": 3
      },
      {
        "nombre": "Laptop HP Pavilion 15-eg0513la Procesador Intel Core i5 8GB RAM, 512GB SSD",
        "procesador": "Intel Core i5-1035G4",
        "grafica": "Intel Iris Xe Graphics 80EU",
        "memoriaRam": "8GB",
        "almacenamiento": "512GB SSD",
        "bateria": 5000,
        "interfaz": "PCI-express",
        "precio": 16499,
        "imagen": "00019749709804l.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 3,
        "marcasLaptopId": 1,
        "tiendaId": 4
      },
      {
    
        "nombre": "Laptop HP 14-dq2531la Intel Core i3 16GB RAM 512GB SSD",
        "procesador": "Intel Core i3-1115G4",
        "grafica": "Intel Graphics",
        "memoriaRam": "16GB",
        "almacenamiento": "512GB SSD",
        "bateria": 6000,
        "interfaz": "PCI-express",
        "precio": 16499,
        "imagen": "00019749716182l.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 3,
        "marcasLaptopId": 1,
        "tiendaId": 5
      },
      {
    
        "nombre": "Laptop Dell Intel Core i5 5ta Generación 8gb Ram 240gb Disco Solido SSD HDMI WiFi Cámara Dell Latitude E5450",
        "procesador": "Intel Core i5-6200U",
        "grafica": "Intel Graphics",
        "memoriaRam": "8GB",
        "almacenamiento": "256GB SSD",
        "bateria": 6000,
        "interfaz": "PCI-express",
        "precio": 5400,
        "imagen": "4617a6f5-7ebd-488c-9480-0eb51a70ef40.e73850c4f2b627f53ee5370c33ce7d3d.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 3,
        "marcasLaptopId": 2,
        "tiendaId": 1
      },
      {
        "nombre": "Laptop Lenovo Ideapad 5 14ALC05 R5 8G 256G 11S",
        "procesador": "AMD Ryzen 5 5500U",
        "grafica": "AMD Radeon Graphics",
        "memoriaRam": "8GB",
        "almacenamiento": "256GB SSD",
        "bateria": 5000,
        "interfaz": "PCI-express",
        "precio": 10399,
        "imagen": "00019637840066l.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 3,
        "marcasLaptopId": 6,
        "tiendaId": 2
      },
      {
        "nombre": "Laptop Lenovo Think V14 G2 IJL 14 Pulgadas HD Intel Celeron Intel UHD 4 GB RAM 128 GB SSD",
        "procesador": "Intel Celeron N N4120",
        "grafica": "Intel UHD Graphics",
        "memoriaRam": "4GB",
        "almacenamiento": "128GB SSD + 1TB HDD",
        "bateria": 5000,
        "interfaz": "PCI-express",
        "precio": 5499,
        "imagen": "169760830837259rek9sige.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 1,
        "marcasLaptopId": 6,
        "tiendaId": 5
      },
      {
        "nombre": "Laptop HP 14-dq0522la 14 pulgadas HD Intel Celeron Intel UHD 600 4 GB RAM 128 GB SSD",
        "procesador": "Intel Celeron N N4120",
        "grafica": "Intel UHD Graphics",
        "memoriaRam": "4GB",
        "almacenamiento": "128GB SSD + 1TB HDD",
        "bateria": 5000,
        "interfaz": "PCI-express",
        "precio": 4899,
        "imagen": "1697608434895vs3im1a0nl.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 1,
        "marcasLaptopId": 1,
        "tiendaId": 5
      },
      {
        "nombre": " Laptop HP 240 G8 14 Pulgadas HD Intel Core i3 Intel UHD Graphics 8 GB RAM 256 GB SSD 1 ",
        "procesador": "Intel Core i3-8145U",
        "grafica": "Intel UHD Graphics",
        "memoriaRam": "8GB",
        "almacenamiento": "256GB SSD + 1TB HDD",
        "bateria": 7000,
        "interfaz": "PCI-express",
        "precio": 7849,
        "imagen": "16976097582487bc881u510g.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 1,
        "marcasLaptopId": 1,
        "tiendaId": 5
      },
      {
        "nombre": "Laptop Thin & Light Asus Chromebook cx1500 15.6 pulgadas HD Intel Celeron Integradas 8 GB RAM",
        "procesador": "Intel Celeron N N4020",
        "grafica": "Intel UHD Graphics",
        "memoriaRam": "8GB",
        "almacenamiento": "256GB HDD",
        "bateria": 7000,
        "interfaz": "PCI-express",
        "precio": 7199,
        "imagen": "16976099284149c30jv3eoq.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 1,
        "marcasLaptopId": 4,
        "tiendaId": 5
      },
      {
        "nombre": "Laptop Thin & Light Asus Chromebook cx1500 15.6 pulgadas HD Intel Celeron Integradas 8 GB RAM",
        "procesador": "Intel Core i5-8200Y",
        "grafica": "Intel UHD Graphics",
        "memoriaRam": "8GB",
        "almacenamiento": "512GB HDD",
        "bateria": 6000,
        "interfaz": "PCI-express",
        "precio": 7199,
        "imagen": "",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 1,
        "marcasLaptopId": 2,
        "tiendaId": 5
      },
      {
        "nombre": "Laptop Dell Latitude 5490 14 pulgadas HD Intel Core i5 Intel UHD 8 GB RAM 256 GB SSD",
        "procesador": "Intel Core i5-8200Y",
        "grafica": "Intel UHD Graphics",
        "memoriaRam": "8GB",
        "almacenamiento": "512GB HDD",
        "bateria": 6000,
        "interfaz": "PCI-express",
        "precio": 7899,
        "imagen": "1697610106551fdod083akfg.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 1,
        "marcasLaptopId": 2,
        "tiendaId": 5
      },
      {
        "nombre": "Laptop 2 en 1 HP Pavilion X360 14 Pulgadas Full HD Intel Core i3 Integradas 8 GB RAM 512 GB SSD",
        "procesador": "Intel Core i3-6006U",
        "grafica": "Intel UHD Graphics",
        "memoriaRam": "8GB",
        "almacenamiento": "512GB SSD + 1TB HDD",
        "bateria": 6000,
        "interfaz": "PCI-express",
        "precio": 15497,
        "imagen": "16976102143779o3ko93ot1o.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 3,
        "marcasLaptopId": 1,
        "tiendaId": 5
      },
      {
        "nombre": "Laptop Huawei Nobele-wfh9al 14 pulgadas full hd Intel Core I5 Intel Iris Xe 16 GB RAM 512 GB SSD",
        "procesador": "Intel Core i5-1340P",
        "grafica": "Intel Iris Xe Graphics 80EU",
        "memoriaRam": "16GB",
        "almacenamiento": "512GB SSD + 1TB HDD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 17099,
        "imagen": "1697646271078k5s7n7k3org.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 3,
        "marcasLaptopId": 10,
        "tiendaId": 5
      },
      {
        "nombre": "Laptop Dell Inspiron 3520 15.6 Pulgadas Full HD Intel Core i5 Intel Iris XE 16 GB RAM 512 GB SSD",
        "procesador": "Intel Core i5-1340P",
        "grafica": "Intel Iris Xe Graphics 80EU",
        "memoriaRam": "16GB",
        "almacenamiento": "512GB SSD + 1TB HDD",
        "bateria": 7000,
        "interfaz": "PCI-express",
        "precio": 14849,
        "imagen": "16976463379073f1fvicjrpo.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 3,
        "marcasLaptopId": 2,
        "tiendaId": 5
      },
      {
        "nombre": "Laptop Dell Inspiron 3525 15.6 pulgadas Full HD AMD Ryzen 7 integradas 16 GB RAM 512 GB SSD",
        "procesador": "AMD Ryzen 7 PRO 6850U",
        "grafica": "AMD Radeon RX 6850M XT",
        "memoriaRam": "16GB",
        "almacenamiento": "512GB SSD + 1TB HDD",
        "bateria": 7000,
        "interfaz": "PCI-express",
        "precio": 16199,
        "imagen": "1697646524975c9n40rml4po.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 4,
        "marcasLaptopId": 2,
        "tiendaId": 5
      },
      {
        "nombre": "Laptop Lenovo 21ENS01E00 15.6 pulgadas Full HD AMD Ryzen 7 AMD Radeon 7 16 GB RAM 512 GB SSD",
        "procesador": "AMD Ryzen 7 PRO 6850U",
        "grafica": "AMD Radeon RX 6850M XT",
        "memoriaRam": "32GB",
        "almacenamiento": "512GB SSD + 1TB HDD",
        "bateria": 7000,
        "interfaz": "PCI-express",
        "precio": 49899,
        "imagen": "1697646609578dovnsige5o.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 4,
        "marcasLaptopId": 6,
        "tiendaId": 5
      },
      {
        "nombre": "Laptop Lenovo 82RN0011US 15.6 Pulgadas Full HD AMD Ryzen 5 12 GB RAM 512 GB SSD",
        "procesador": "AMD Ryzen 5 6600H",
        "grafica": "AMD Radeon RX 6850M XT",
        "memoriaRam": "12GB",
        "almacenamiento": "512GB SSD + 1TB HDD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 12399,
        "imagen": "1697646706056safft6n1qao.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 4,
        "marcasLaptopId": 6,
        "tiendaId": 5
      },
      {
        "nombre": "Laptop Acer NX.A89AL.002 15.6 Pulgadas Full HD AMD Ryzen 3 8 GB RAM 256 GB SSD",
        "procesador": "AMD Ryzen 3 PRO 4450U",
        "grafica": "AMD Radeon RX 6850M XT",
        "memoriaRam": "8GB",
        "almacenamiento": "256GB SSD + 1TB HDD",
        "bateria": 7000,
        "interfaz": "PCI-express",
        "precio": 13299,
        "imagen": "1697646792289ijeuckruhr8.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 4,
        "marcasLaptopId": 7,
        "tiendaId": 5
      },
      {
        "nombre": "Laptop HP 7E8F7LT 14 pulgadas HD AMD Ryzen 3 Integradas 8 GB RAM 512 GB SSD",
        "procesador": "AMD Ryzen 3 3200U",
        "grafica": "AMD Radeon RX 6850M XT",
        "memoriaRam": "8GB",
        "almacenamiento": "512GB SSD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 8499,
        "imagen": "1697646907643r13s1gr43ag.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 4,
        "marcasLaptopId": 1,
        "tiendaId": 5
      },
      {
        "nombre": "Laptop Lenovo 82RN0011US 15.6 Pulgadas Full HD AMD Ryzen 5 12 GB RAM 512 GB SSD",
        "procesador": "AMD Ryzen 5 3580U",
        "grafica": "AMD Radeon RX 6850M XT",
        "memoriaRam": "12GB",
        "almacenamiento": "512GB SSD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 12399,
        "imagen": "1697647001434qnocvf4k3p.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 4,
        "marcasLaptopId": 6,
        "tiendaId": 5
      },
      {
        "nombre": "Laptop Lenovo Ideapad 3 15ALC6 15.6 Pulgadas Full HD AMD Ryzen 7 12 GB RAM 512 GB SSD",
        "procesador": "AMD Ryzen 7 3700U",
        "grafica": "AMD Radeon RX 6850M XT",
        "memoriaRam": "12GB",
        "almacenamiento": "512GB SSD",
        "bateria": 8000,
        "interfaz": "NVMe PCI-express",
        "precio": 13499,
        "imagen": "16976470874216ts2vnt3r98.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 4,
        "marcasLaptopId": 6,
        "tiendaId": 5
      },
      {
        "nombre": "Laptop ASUS M1603Q 16 Pulgadas HD AMD Ryzen 7 AMD Radeon 12 GB RAM 512 GB SSD",
        "procesador": "AMD Ryzen 7 3700U",
        "grafica": "AMD Radeon RX 6850M XT",
        "memoriaRam": "12GB",
        "almacenamiento": "512GB SSD",
        "bateria": 8000,
        "interfaz": "NVMe PCI-express",
        "precio": 13999,
        "imagen": "16976473671646o26k3hadco.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 4,
        "marcasLaptopId": 4,
        "tiendaId": 5
      },
      {
        "nombre": "Laptop ASUS B1400CEAE-I78G512-P2 14 Pulgadas Full HD Intel Core i7 8 GB RAM 512 GB SSD",
        "procesador": "Intel Core i7-1160G7",
        "grafica": "Nvidia RTX 4060",
        "memoriaRam": "8GB",
        "almacenamiento": "512GB SSD",
        "bateria": 8000,
        "interfaz": "NVMe PCI-express",
        "precio": 19799,
        "imagen": "1697647446405g8hlebfjp3o.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 4,
        "marcasLaptopId": 4,
        "tiendaId": 5
      },
      {
        "nombre": "Laptop Thin & Light ASUS Vivobook 15 15.6 Pulgadas HD Intel Core i3 Intel UHD Graphics 8 GB RAM 256 GB SSD",
        "procesador": "Intel Core i3-1125G4",
        "grafica": "Nvidia RTX 4060",
        "memoriaRam": "8GB",
        "almacenamiento": "512GB SSD",
        "bateria": 8000,
        "interfaz": "NVMe PCI-express",
        "precio": 7199,
        "imagen": "1697647555908go5f2jhr48g.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 4,
        "marcasLaptopId": 4,
        "tiendaId": 5
      },
      {
        "nombre": "Laptop thin & light Acer Aspire 3 15.6 pulgadas Full HD Intel Core i3 Intel UHD Graphics 8 GB RAM 512 GB SSD",
        "procesador": "Intel Core i3-1125G4",
        "grafica": "Intel Iris Xe Graphics 80EU",
        "memoriaRam": "8GB",
        "almacenamiento": "512GB SSD",
        "bateria": 8000,
        "interfaz": "NVMe PCI-express",
        "precio": 13499,
        "imagen": "1697647644510h25ugbmi958.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 4,
        "marcasLaptopId": 7,
        "tiendaId": 5
      },
      {
        "nombre": "Laptop MSI A11MU-652 15.6 Pulgadas Full HD Intel Core i7 Intel HD Graphics 520 8 GB RAM 1 TB SSD",
        "procesador": "Intel Core i7-8750H",
        "grafica": "AMD Radeon 760M",
        "memoriaRam": "8GB",
        "almacenamiento": "512GB SSD",
        "bateria": 8000,
        "interfaz": "NVMe PCI-express",
        "precio": 22989,
        "imagen": "16976477132014k2dalctt8.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 4,
        "marcasLaptopId": 8,
        "tiendaId": 5
      },
      {
        "nombre": "Laptop Lenovo ThinkPad L570 15.6 Pulgadas HD Intel HD Graphics 620 Intel Core i5 8 GB RAM 500 GB HDD",
        "procesador": "Intel Core i5-1155G7",
        "grafica": "Intel Graphics",
        "memoriaRam": "8GB",
        "almacenamiento": "512GB HDD",
        "bateria": 8000,
        "interfaz": "NVMe PCI-express",
        "precio": 10532,
        "imagen": "1697647810899i0hh8fkjjhg.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 4,
        "marcasLaptopId": 6,
        "tiendaId": 5
      },
      {
        "nombre": "Laptop Asus P1440FA 14 Pulgadas HD Intel Core i5 Intel UHD 620 8 GB RAM 1 TB HDD",
        "procesador": "Intel Core i5-1155G7",
        "grafica": "Intel Graphics",
        "memoriaRam": "8GB",
        "almacenamiento": "512GB HDD",
        "bateria": 8000,
        "interfaz": "NVMe PCI-express",
        "precio": 14999,
        "imagen": "1697647905601jvmfgaho6d.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 4,
        "marcasLaptopId": 4,
        "tiendaId": 5
      },
      {
        "nombre": "Laptop Dell Latitude 5430 14 Pulgadas HD Intel Core i5 Intel Iris XE 8 GB RAM 256 GB SSD",
        "procesador": "Intel Core i5-1155G7",
        "grafica": "Intel Iris Xe Graphics 80EU",
        "memoriaRam": "8GB",
        "almacenamiento": "256GB SSD",
        "bateria": 7000,
        "interfaz": "NVMe PCI-express",
        "precio": 21914,
        "imagen": "1697647961420nmiifq2tek.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 4,
        "marcasLaptopId": 2,
        "tiendaId": 5
      },
      {
        "nombre": "Laptop Dell Latitude 3420 14 Pulgadas HD Intel Core i5 Intel Iris XE 8 GB RAM 256 GB SSD",
        "procesador": "Intel Core i5-1155G7",
        "grafica": "Intel Iris Xe Graphics 80EU",
        "memoriaRam": "8GB",
        "almacenamiento": "256GB SSD",
        "bateria": 7000,
        "interfaz": "NVMe PCI-express",
        "precio": 17999,
        "imagen": "1697648026060p1da9pijhig.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 4,
        "marcasLaptopId": 2,
        "tiendaId": 5
      },
      {
    
        "nombre": "Laptop Dell Latitude 7430 14 Pulgadas Full HD Intel Core i7 Intel Iris XE 16 GB RAM 512 GB SSD",
        "procesador": "Intel Core i7-8750H",
        "grafica": "Intel Iris Xe Graphics 80EU",
        "memoriaRam": "8GB",
        "almacenamiento": "512GB SSD + 1TB HDD",
        "bateria": 8000,
        "interfaz": "NVMe PCI-express",
        "precio": 43999,
        "imagen": "16976480917032o5jfeku82.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 4,
        "marcasLaptopId": 2,
        "tiendaId": 5
      },
      {
    
        "nombre": "Laptop Lenovo 82H701FYUS 14 Pulgadas Full HD Intel Core i5 Intel Iris XE 8 GB RAM 512 GB SSD",
        "procesador": "Intel Core i5-11320H",
        "grafica": "Intel Iris Xe Graphics 80EU",
        "memoriaRam": "8GB",
        "almacenamiento": "512GB SSD + 1TB HDD",
        "bateria": 8000,
        "interfaz": "NVMe PCI-express",
        "precio": 43999,
        "imagen": "",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 4,
        "marcasLaptopId": 6,
        "tiendaId": 5
      },
      {
    
        "nombre": "Laptop Lenovo 82H701FYUS 14 Pulgadas Full HD Intel Core i5 Intel Iris XE 8 GB RAM 512 GB SSD",
        "procesador": "Intel Core i5-11320H",
        "grafica": "Intel Iris Xe Graphics 80EU",
        "memoriaRam": "8GB",
        "almacenamiento": "512GB SSD + 1TB HDD",
        "bateria": 8000,
        "interfaz": "NVMe PCI-express",
        "precio": 10695,
        "imagen": "1697648166101h0jrpo0src.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 4,
        "marcasLaptopId": 6,
        "tiendaId": 5
      },
      {
    
        "nombre": "Laptop Lenovo ThinkBook 14s G2 ITL 14 pulgadas Full HD Intel Iris XE Intel Core i5 16 GB RAM 256 GB SSD",
        "procesador": "Intel Core i5-11320H",
        "grafica": "Intel Iris Xe Graphics 80EU",
        "memoriaRam": "8GB",
        "almacenamiento": "256GB SSD",
        "bateria": 8000,
        "interfaz": "NVMe PCI-express",
        "precio": 23080,
        "imagen": "1697648252068kse2fgfdjv.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 4,
        "marcasLaptopId": 6,
        "tiendaId": 5
      },
      {
    
        "nombre": "Laptop Lenovo 82FG01U0US 15.6 Pulgadas Full HD Intel Core i5 Intel Iris Xe 8 GB RAM 256 GB SSD",
        "procesador": "Intel Core i5-11320H",
        "grafica": "Intel Iris Xe Graphics 80EU",
        "memoriaRam": "8GB",
        "almacenamiento": "256GB SSD",
        "bateria": 8000,
        "interfaz": "NVMe PCI-express",
        "precio": 11799,
        "imagen": "16976483111368sapduqh7u8.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 4,
        "marcasLaptopId": 6,
        "tiendaId": 5
      },
      {
    
        "nombre": "Laptop HP 14-DQ0527LA 14\" Intel Celeron  quad 8 GB RAM de 256 GB SSD Plata",
        "procesador": "Intel Celeron N N4020",
        "grafica": "Intel Iris Xe Graphics 80EU",
        "memoriaRam": "8GB",
        "almacenamiento": "256GB SSD",
        "bateria": 9000,
        "interfaz": "NVMe PCI-express",
        "precio": 8799,
        "imagen": "1697648514311gnp78f2jgf8.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 4,
        "marcasLaptopId": 1,
        "tiendaId": 1
      },
      {
    
        "nombre": "Laptop Lenovo IdeaPad 14\" Windows 11 Intel Celeron 4 GB RAM 128 GB SSD Gris",
        "procesador": "Intel Celeron N N4020",
        "grafica": "Intel UHD Graphics",
        "memoriaRam": "4GB",
        "almacenamiento": "128GB SSD + 1TB HDD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 8999,
        "imagen": "1697649784429g51cblivbsg.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 1,
        "marcasLaptopId": 6,
        "tiendaId": 1
      },
      {
    
        "nombre": "Laptop Acer A315-35-C3RU 15.6\" Windows 11 Intel Celeron 8 GB RAM 1 TB HDD Plata",
        "procesador": "Intel Celeron N N4020",
        "grafica": "Intel UHD Graphics",
        "memoriaRam": "8GB",
        "almacenamiento": "128GB SSD + 1TB HDD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 9999,
        "imagen": "1697649849945t42i42najk.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 1,
        "marcasLaptopId": 7,
        "tiendaId": 1
      },
      {
    
        "nombre": "Laptop Lenovo IP 3 15ALC6 R7 15.6\" Windows 11 Home AMD Ryzen 7 16 GB RAM de 512 GB Dorada",
        "procesador": "AMD Ryzen 7 3700U",
        "grafica": "AMD Radeon 660M",
        "memoriaRam": "16GB",
        "almacenamiento": "512GB SSD + 1TB HDD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 19999,
        "imagen": "1697649954181avrqmj6chf.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 1,
        "marcasLaptopId": 6,
        "tiendaId": 1
      },
      {
    
        "nombre": "Laptop Gamer HP Victus 15-FB0122LA 15.6\" AMD Ryzen 5 NVIDIA GeForce GTX 1650 8 GB RAM 512 SSD Negra",
        "procesador": "AMD Ryzen 5 7520U",
        "grafica": "Nvidia GTX 1650 Max-Q",
        "memoriaRam": "16GB",
        "almacenamiento": "512GB SSD + 1TB HDD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 18499,
        "imagen": "1697650041454gpvgm5cicsg.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 1,
        "marcasLaptopId": 1,
        "tiendaId": 1
      },
      {
    
        "nombre": "Laptop Gamer Asus FX506HCB-HN144W Windows 11 Intel Core i5 NVIDIA GeForce RTX 3050 8 GB RAM 512 SSD Negra",
        "procesador": "Intel Core i5-1155G7",
        "grafica": "Nvidia RTX 3050Ti",
        "memoriaRam": "8GB",
        "almacenamiento": "512GB SSD + 1TB HDD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 19999,
        "imagen": "",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 1,
        "marcasLaptopId": 4,
        "tiendaId": 1
      },
      {
    
        "nombre": "Laptop Gamer Lenovo Ideapad Gaming 3 15.6\" Windows 11 Intel Core i5 Nvidia GeForce GTX 1650 16 GB RAM 512 SSD Negro",
        "procesador": "Intel Core i5-1155G7",
        "grafica": "Nvidia GTX 1650",
        "memoriaRam": "16GB",
        "almacenamiento": "512GB SSD + 1TB HDD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 19999,
        "imagen": "1697650229917pvjcflpca28.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 1,
        "marcasLaptopId": 6,
        "tiendaId": 1
      },
      {
    
        "nombre": "Laptop Lenovo Ideapad Slim 3 15.6\" Windows 11 Intel Core i3 8 GB RAM 256 SSD Azul",
        "procesador": "Intel Core i3-N305",
        "grafica": "Intel Graphics",
        "memoriaRam": "8GB",
        "almacenamiento": "256GB SSD + 1TB HDD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 13999,
        "imagen": "1697650317961s698c2hsmn.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 1,
        "marcasLaptopId": 6,
        "tiendaId": 1
      },
      {
    
        "nombre": "Laptop Gamer Asus FX506HF-HN010W 15.6\" Windows 11 Intel Core i5 8 GB RAM 512 GB SSD Negro + Mochila",
        "procesador": "Intel Core i5-11320H",
        "grafica": "Intel Graphics",
        "memoriaRam": "8GB",
        "almacenamiento": "512GB SSD + 1TB HDD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 17999,
        "imagen": "16976503801844o7u495tk1g.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 1,
        "marcasLaptopId": 4,
        "tiendaId": 1
      },
      {
    
        "nombre": "Laptop Acer Nitro 5 de 15.6\" Windows 11 Intel Core i5 NVIDIA GeForce RTX 3050 8 GB RAM 512 GB SSD Negra",
        "procesador": "Intel Core i5-11320H",
        "grafica": "Nvidia RTX 3050",
        "memoriaRam": "8GB",
        "almacenamiento": "512GB SSD + 1TB HDD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 25999,
        "imagen": "1697650512781v6ft9ntlsjo.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 1,
        "marcasLaptopId": 7,
        "tiendaId": 1
      },
      {
    
        "nombre": "Laptop HP Pavilion 15-EG0510LA 15.6\" Intel Core i5 12 GB RAM de 512 GB SSD Azul",
        "procesador": "Intel Core i5-11320H",
        "grafica": "Intel UHD Graphics",
        "memoriaRam": "12GB",
        "almacenamiento": "512GB SSD + 1TB HDD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 18999,
        "imagen": "1697650574728tcddrovdu2.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 1,
        "marcasLaptopId": 1,
        "tiendaId": 1
      },
      {
    
        "nombre": "Laptop Lenovo Thinkpad T470 14'' Intel Core I5 6ta Generación 8 GB RAM 256 GB SSD color Negro Reacondicionado",
        "procesador": "Intel Core i5-11320H",
        "grafica": "Intel UHD Graphics",
        "memoriaRam": "8GB",
        "almacenamiento": "256GB SSD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 5499,
        "imagen": "1697650879120iuhnch8l08o.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 1,
        "marcasLaptopId": 6,
        "tiendaId": 1
      },
      {
    
        "nombre": "Laptop Lenovo T470- 14''-intel Core I5 7a- 16gb Ram-1tb Reacondicionado",
        "procesador": "Intel Core i5-11320H",
        "grafica": "Intel UHD Graphics",
        "memoriaRam": "16GB",
        "almacenamiento": "256GB SSD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 7999,
        "imagen": "1697650929068dl23qdf18j.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 1,
        "marcasLaptopId": 6,
        "tiendaId": 1
      },
      {
    
        "nombre": "Laptop Lenovo Thinkpad T490s 14'' Intel Core I7-8a Gen 16gb Ram 128gb SSD color Negro Reacondicionado",
        "procesador": "Intel Core i7-1195G7",
        "grafica": "Intel UHD Graphics",
        "memoriaRam": "16GB",
        "almacenamiento": "128GB SSD + 1TB HDD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 8499,
        "imagen": "1697650983324p9ldegktv3g.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 1,
        "marcasLaptopId": 6,
        "tiendaId": 1
      },
      {
    
        "nombre": "Laptop Lenovo T480s Intel Core I7 8va Gen 16gb RAM/512gb SSD Windows 10 Pro 14'' Reacondicionada",
        "procesador": "Intel Core i7-1195G7",
        "grafica": "Intel UHD Graphics",
        "memoriaRam": "16GB",
        "almacenamiento": "512GB SSD + 1TB HDD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 9399,
        "imagen": "1697651031048j9r9eil0j18.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 1,
        "marcasLaptopId": 6,
        "tiendaId": 1
      },
      {
    
        "nombre": "Laptop Dell E5480 - 14'' -intel Core I5 De 7a - 16gb Ram 500 Gb Hdd Reacondicionado",
        "procesador": "Intel Core i5-1245U",
        "grafica": "Intel UHD Graphics",
        "memoriaRam": "16GB",
        "almacenamiento": "512GB HDD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 6999,
        "imagen": "16976510956549ljq6tv9kd.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 1,
        "marcasLaptopId": 2,
        "tiendaId": 1
      },
      {
    
        "nombre": "Laptop Dell Latitude 5480 - 14'', Intel Core I5-7a Generación, 16gb Ram, 256gb Ssd, Windows 10 Pro Reacondicionado",
        "procesador": "Intel Core i5-1245U",
        "grafica": "Intel UHD Graphics",
        "memoriaRam": "16GB",
        "almacenamiento": "256GB SSD + 1TB HDD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 6999,
        "imagen": "1697651139632odkihapgjlo.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 1,
        "marcasLaptopId": 2,
        "tiendaId": 1
      },
      {
    
        "nombre": "Laptop Dell Latitude 7280 - 12'' - Intel Core I7-6a Gen - 16gb Ram - 512gb Ssd -reacondicionado",
        "procesador": "Intel Core i7-1255U",
        "grafica": "Intel UHD Graphics",
        "memoriaRam": "16GB",
        "almacenamiento": "512GB SSD + 1TB HDD",
        "bateria": 7000,
        "interfaz": "PCI-express",
        "precio": 8999,
        "imagen": "1697651197136ogop1k1oqdo.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 3,
        "marcasLaptopId": 2,
        "tiendaId": 1
      },
      {
    
        "nombre": "Laptop Lenovo IdeaPad 1 AMD Athlon Silver 15.6 pulg. 256gb SSD 8gb",
        "procesador": "AMD Ryzen 5 PRO 5650U",
        "grafica": "AMD Radeon Graphics",
        "memoriaRam": "8GB",
        "almacenamiento": "256GB SSD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 5999,
        "imagen": "16976513083381lt77rdcj08.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 3,
        "marcasLaptopId": 6,
        "tiendaId": 2
      },
      {
    
        "nombre": "Laptop Lenovo IdeaPad 3 Intel Core i7 15.6 pulg. 512gb SSD 8gb",
        "procesador": "Intel Core i7-1365U",
        "grafica": "Intel UHD Graphics",
        "memoriaRam": "8GB",
        "almacenamiento": "512GB SSD + 1TB HDD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 16999,
        "imagen": "16976513869669o35fober98.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 3,
        "marcasLaptopId": 6,
        "tiendaId": 2
      },
      {
    
        "nombre": "Laptop Acer Surface Go 2 Intel Core i5 12.4 pulg. 128 gb SSD 8gb RAM",
        "procesador": "Intel Core i5-11400H",
        "grafica": "Intel UHD Graphics",
        "memoriaRam": "8GB",
        "almacenamiento": "128GB SSD + 1TB HDD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 16199,
        "imagen": "16976514797377erhp0id96.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 3,
        "marcasLaptopId": 7,
        "tiendaId": 2
      },
      {
    
        "nombre": "Laptop Acer Surface 5 Intel Core i7 13.5 pulg. 512gb SSD 16gb RAM",
        "procesador": "Intel Core i7-1270P",
        "grafica": "Intel UHD Graphics",
        "memoriaRam": "16GB",
        "almacenamiento": "512GB SSD + 1TB HDD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 16199,
        "imagen": "169765153917989d85cjqbu.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 3,
        "marcasLaptopId": 7,
        "tiendaId": 2
      },
      {
    
        "nombre": "Laptop con Funda Asus Zenbook 14 Oled Intel Core i5 14 pulg. 512gb SSD 16gb RAM",
        "procesador": "Intel Core i5-12450H",
        "grafica": "Intel UHD Graphics",
        "memoriaRam": "16GB",
        "almacenamiento": "512GB SSD + 1TB HDD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 23999,
        "imagen": "1697651622090mm0fb1mnv9.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 3,
        "marcasLaptopId": 4,
        "tiendaId": 2
      },
      {
    
        "nombre": "Laptop 2 en 1 Microsoft Surface Pro 9 Intel Core i5 13 Pulg. 256gb SSD 8gb RAM Azul",
        "procesador": "Intel Core i5-12450H",
        "grafica": "Intel UHD Graphics",
        "memoriaRam": "8GB",
        "almacenamiento": "256GB SSD + 1TB HDD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 27199,
        "imagen": "1697651678045d3agpaldt6g.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 3,
        "marcasLaptopId": 9,
        "tiendaId": 2
      },
      {
    
        "nombre": "Laptop 2 en 1 Microsoft Surface Pro 9 Intel Core i7 13 Pulg. 256gb SSD 8gb RAM Verde",
        "procesador": "Intel Core i7-1360P",
        "grafica": "Intel UHD Graphics",
        "memoriaRam": "8GB",
        "almacenamiento": "256GB SSD + 1TB HDD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 27199,
        "imagen": "1697651735952099lcfkop58.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 3,
        "marcasLaptopId": 9,
        "tiendaId": 2
      },
      {
    
        "nombre": "Laptop HP Pavilion 2 en 1 14EK0001LA Intel Core i3 14 pulg. 512gb SSD 8gb RAM",
        "procesador": "Intel Core i3-1125G4",
        "grafica": "Intel UHD Graphics",
        "memoriaRam": "8GB",
        "almacenamiento": "512GB SSD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 15499,
        "imagen": "1697651816482l46sfgmh32g.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 3,
        "marcasLaptopId": 1,
        "tiendaId": 2
      },
      {
    
        "nombre": "Laptop Gamer Acer Nitro 5 GeForce RTX 3050 Intel Core i5 15.6 pulg. 512gb SSD 8gb RAM",
        "procesador": "Intel Core i5-1230U",
        "grafica": "Nvidia RTX 3050",
        "memoriaRam": "8GB",
        "almacenamiento": "512GB SSD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 17999,
        "imagen": "1697652022919k9k8pp8aecg.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 3,
        "marcasLaptopId": 7,
        "tiendaId": 2
      },
      {
    
        "nombre": "Laptop Gamer Asus TUF F15 GeForce 2050 RTX Intel Core i5 15.6 pulg. 512gb SSD 8gb RAM",
        "procesador": "Intel Core i5-1230U",
        "grafica": "Nvidia RTX 2050",
        "memoriaRam": "8GB",
        "almacenamiento": "512GB SSD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 17499,
        "imagen": "169765208196432u7j1tsuag.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 3,
        "marcasLaptopId": 4,
        "tiendaId": 2
      },
      {
    
        "nombre": "Laptop Gamer Acer Nitro 5 GeForce RTX 3050 Intel Core i5 15.6 pulg. 512gb SSD 8gb RAM",
        "procesador": "Intel Core i5-1230U",
        "grafica": "Nvidia RTX 3050",
        "memoriaRam": "8GB",
        "almacenamiento": "512GB SSD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 17999,
        "imagen": "16976521640103j7mvcg8n08.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 3,
        "marcasLaptopId": 7,
        "tiendaId": 2
      },
      {
    
        "nombre": "Laptop Gamer Acer Nitro 5 AN515-58-71EC GeForce RTX 3050 Intel Core i7 15.6 pulg. 512gb SSD 12gb RAM",
        "procesador": "Intel Core i7-1250U",
        "grafica": "Nvidia RTX 3050",
        "memoriaRam": "12GB",
        "almacenamiento": "512GB SSD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 29999,
        "imagen": "169765221872423i3ds6b03o.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 3,
        "marcasLaptopId": 7,
        "tiendaId": 2
      },
      {
    
        "nombre": "Laptop Gamer HP Victus 15-fb0122la GeForce GTX 1650 AMD Ryzen 5 15.6 pulg. 512gb SSD 8gb RAM",
        "procesador": "AMD Ryzen 5 PRO 5675U",
        "grafica": "Nvidia GTX 1650Ti Max-Q",
        "memoriaRam": "8GB",
        "almacenamiento": "512GB SSD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 18499,
        "imagen": "1697652298649o8dkk1i12t8.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 3,
        "marcasLaptopId": 1,
        "tiendaId": 2
      },
      {
    
        "nombre": "Laptop Acer Aspire 5 Intel Core i3 15.6 pulg. 512gb SSD 8gb RAM",
        "procesador": "Intel Core i3-1220P",
        "grafica": "Intel Graphics",
        "memoriaRam": "8GB",
        "almacenamiento": "512GB SSD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 8999,
        "imagen": "1697653641567fc268hj7rhg.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 3,
        "marcasLaptopId": 7,
        "tiendaId": 2
      },
      {
    
        "nombre": "Laptop Acer Aspire 3 AMD Ryzen 5 15.6 pulg. 512 SSD 8gb RAM",
        "procesador": "AMD Ryzen 5 5600U",
        "grafica": "AMD Radeon 780M",
        "memoriaRam": "8GB",
        "almacenamiento": "512GB SSD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 14999,
        "imagen": "169765369385615o4fpia71g.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 3,
        "marcasLaptopId": 7,
        "tiendaId": 2
      },
      {
    
        "nombre": "Laptop Lenovo Yoga Slim 6 14IRP8 Intel Core i5 14 pulg. 512gb SSD 16gb RAM",
        "procesador": "Intel Core i5-1345U",
        "grafica": "Intel UHD Graphics",
        "memoriaRam": "16GB",
        "almacenamiento": "512GB SSD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 26999,
        "imagen": "1697653749375pvh9iau6f18.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 3,
        "marcasLaptopId": 6,
        "tiendaId": 2
      },
      {
    
        "nombre": "Laptop Lenovo IdeaPad 3 15ALC6 AMD Ryzen 5 15.6 pulg. 1tb 256gb SSD 8gb RAM",
        "procesador": "AMD Ryzen 5 5600U",
        "grafica": "AMD Radeon Graphics",
        "memoriaRam": "8GB",
        "almacenamiento": "256GB SSD + 1TB HDD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 16999,
        "imagen": "1697653822164ivhh3pnnaq.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 3,
        "marcasLaptopId": 6,
        "tiendaId": 2
      },
      {
    
        "nombre": "Bundle Laptop HP 14-em0002la AMD Ryzen 5 14 pulg. 512gb SSD 8gb RAM más Impresora",
        "procesador": "AMD Ryzen 5 5600U",
        "grafica": "AMD Radeon Graphics",
        "memoriaRam": "8GB",
        "almacenamiento": "512GB SSD + 1TB HDD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 13999,
        "imagen": "16976538843328dila2f8tf8.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 3,
        "marcasLaptopId": 1,
        "tiendaId": 2
      },
      {
    
        "nombre": "Laptop Gamer MSI Katana 15 GeForce RTX 4060 Intel Core i7 15.6 pulg. 1TB SSD 16gb RAM Negro",
        "procesador": "Intel Core i7-1355U",
        "grafica": "Nvidia RTX 4060",
        "memoriaRam": "16GB",
        "almacenamiento": "1TB SSD + 1TB HDD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 26999,
        "imagen": "1697654014754dubgg58ifcg.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 3,
        "marcasLaptopId": 8,
        "tiendaId": 2
      },
      {
    
        "nombre": "Laptop Gamer Acer Nitro 5 GeForce RTX 3050 Intel Core i5 15.6 pulg. 512gb SSD 8gb RAM",
        "procesador": "Intel Core i5-11400H",
        "grafica": "Nvidia RTX 3050 (6GB)",
        "memoriaRam": "8GB",
        "almacenamiento": "512GB SSD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 17999,
        "imagen": "16976541169766rkv5mrtc78.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 3,
        "marcasLaptopId": 7,
        "tiendaId": 2
      },
      {
    
        "nombre": "Bundle Laptop Gamer HP 15 Victus 15-fb0122la GeForce GTX 1650 AMD Ryzen 5 15.6 pulg. 512gb SSD 8gb RAM más Audífonos Hyper X Stinger Core",
        "procesador": "AMD Ryzen 5 6600U",
        "grafica": "Nvidia GTX 1650Ti",
        "memoriaRam": "8GB",
        "almacenamiento": "512GB SSD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 18999,
        "imagen": "1697654192728jh9v3fvhogo.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 3,
        "marcasLaptopId": 1,
        "tiendaId": 2
      },
      {
    
        "nombre": "Laptop Gamer Acer Nitro 5 AN515-58-71EC GeForce RTX 3050 Intel Core i7 15.6 pulg. 512gb SSD 12gb RAM",
        "procesador": "Intel Core i7-1260P",
        "grafica": "Nvidia RTX 3050",
        "memoriaRam": "12GB",
        "almacenamiento": "512GB SSD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 29999,
        "imagen": "1697654290974gbp2m02mfqg.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 3,
        "marcasLaptopId": 7,
        "tiendaId": 2
      },
      {
    
        "nombre": "Laptop Gamer HP 16 Victus 16-d0536la GeForce RTX 3050 Intel Core i5 16.1 pulg. 512gb SSD 16gb RAM",
        "procesador": "Intel Core i5-12450H",
        "grafica": "Nvidia RTX 3050",
        "memoriaRam": "16GB",
        "almacenamiento": "512GB SSD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 25999,
        "imagen": "1697654365283v97mq5mtnp8.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 3,
        "marcasLaptopId": 1,
        "tiendaId": 2
      },
      {
    
        "nombre": "Laptop HP 15-fd0000la Intel Core i3 8 Núcleos 8GB RAM 512GB SSD Azul",
        "procesador": "Intel Core i3-1315U",
        "grafica": "Intel UHD Graphics",
        "memoriaRam": "8GB",
        "almacenamiento": "512GB SSD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 8499,
        "imagen": "1697654456687204uo4gvu7g.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 3,
        "marcasLaptopId": 1,
        "tiendaId": 3
      },
      {
    
        "nombre": "Laptop HP 14-dq2531la Intel Core i3 16GB RAM 512GB SSD",
        "procesador": "Intel Core i3-1315U",
        "grafica": "Intel UHD Graphics",
        "memoriaRam": "8GB",
        "almacenamiento": "512GB SSD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 9999,
        "imagen": "169765451944275efoju9i08.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 3,
        "marcasLaptopId": 1,
        "tiendaId": 3
      },
      {
    
        "nombre": "Laptop HP 14-dq2533la Procesador Intel Core i5 Gen. 11 8GB RAM 512GB SSD 14 Pulgadas HD Plateado",
        "procesador": "Intel Core i5-1245U",
        "grafica": "Intel UHD Graphics",
        "memoriaRam": "8GB",
        "almacenamiento": "512GB SSD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 12399,
        "imagen": "1697654592910ipgkp7g19cg.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 3,
        "marcasLaptopId": 1,
        "tiendaId": 3
      },
      {
    
        "nombre": "MacBook Air Apple MGN63LA/A M1 8GB RAM 256GB SSD",
        "procesador": "Intel Core i5-11320H",
        "grafica": "Apple M1 Max",
        "memoriaRam": "8GB",
        "almacenamiento": "256GB SSD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 16999,
        "imagen": "16976547192908bfrn32sf0g.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 3,
        "marcasLaptopId": 5,
        "tiendaId": 3
      },
      {
    
        "nombre": "Macbook Air Apple Intel Core i5 8GB RAM 128GB SSD MMGF2LL/A Reacondicionado",
        "procesador": "Intel Core i5-11320H",
        "grafica": "Apple M1",
        "memoriaRam": "8GB",
        "almacenamiento": "128GB SSD + 1TB HDD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 6199,
        "imagen": "16976548086214rlmhg1lf0o.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 11,
        "marcasLaptopId": 5,
        "tiendaId": 3
      },
      {
    
        "nombre": "Macbook Air 2017 Apple Intel Core i5 8GB RAM 128GB SSD MQD32LL/A Reacondicionado",
        "procesador": "Intel Core i5-11320H",
        "grafica": "Apple M1",
        "memoriaRam": "8GB",
        "almacenamiento": "128GB SSD + 1TB HDD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 5999,
        "imagen": "1697654874189r9o4ugfmffo.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 9,
        "marcasLaptopId": 5,
        "tiendaId": 3
      },
      {
    
        "nombre": "Laptop Gamer Asus ROG ZEPHYRUS Ryzen 7 GeForce RTX 3060 16GB 512GB SSD",
        "procesador": "AMD Ryzen 7 4700U",
        "grafica": "Nvidia RTX 3060",
        "memoriaRam": "16GB",
        "almacenamiento": "512GB SSD + 1TB HDD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 17999,
        "imagen": "1697654970440tqvnavk1d18.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 4,
        "marcasLaptopId": 4,
        "tiendaId": 3
      },
      {
    
        "nombre": "Laptop Gamer DELL 3515 Ryzen 5  12GB 1TB 256GB SSD 94JM5-V2 Dell Inspiron 3515",
        "procesador": "AMD Ryzen 5 PRO 5650U",
        "grafica": "Intel Graphics",
        "memoriaRam": "12GB",
        "almacenamiento": "256GB SSD + 1TB HDD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 11699,
        "imagen": "169765505941254j1c8cn4b.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 4,
        "marcasLaptopId": 2,
        "tiendaId": 3
      },
      {
    
        "nombre": "Laptop HP 240 G8 Core i5 1135G7 8GB M.2 256GB SSD W11H 14 HP 79L97LT",
        "procesador": "Intel Core i5-11500H",
        "grafica": "Intel Graphics",
        "memoriaRam": "8GB",
        "almacenamiento": "256GB SSD + 1TB HDD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 8830,
        "imagen": "169765510937423n2ru6jgc.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 4,
        "marcasLaptopId": 1,
        "tiendaId": 3
      },
      {
    
        "nombre": "Laptops DELL Vostro 5310 - 13.3 pulgadas, Intel Core i5, 11300H, 8 GB, Windows 10 Pro, 256 GB Dell 81HVC",
        "procesador": "Intel Core i5-11500H",
        "grafica": "Intel Graphics",
        "memoriaRam": "8GB",
        "almacenamiento": "256GB SSD + 1TB HDD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 21895,
        "imagen": "1697655167874p0s23ladj78.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 4,
        "marcasLaptopId": 2,
        "tiendaId": 3
      },
      {
    
        "nombre": "Laptop HP 745 G5- 14\"- AMD Ryzen 3 Pro- 16GB RAM- 512GB SSD- Reacondicionado.",
        "procesador": "AMD Ryzen 3 5300U",
        "grafica": "Intel Graphics",
        "memoriaRam": "16GB",
        "almacenamiento": "512GB SSD + 1TB HDD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 9999,
        "imagen": "169765523232512egen7je88.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 4,
        "marcasLaptopId": 1,
        "tiendaId": 3
      },
      {
    
        "nombre": "Laptop DELL Inspiron 13 - 13.3 pulgadas, Intel Core i5, i5 11320H, 8 GB, Windows 11 Home, 512 GB Dell FMV4K",
        "procesador": "Intel Core i5-1135G7",
        "grafica": "Intel Graphics",
        "memoriaRam": "8GB",
        "almacenamiento": "512GB SSD + 1TB HDD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 21699,
        "imagen": "16976552912314pbo8s6bkv.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 3,
        "marcasLaptopId": 2,
        "tiendaId": 3
      },
      {
    
        "nombre": "Lap Top Dell Latitude 3160",
        "procesador": "Intel Pentium Gold 6405U",
        "grafica": "Intel Graphics",
        "memoriaRam": "4GB",
        "almacenamiento": "256GB HDD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 4799,
        "imagen": "1697655370031hoohm42kaag.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 1,
        "marcasLaptopId": 2,
        "tiendaId": 3
      },
      {
    
        "nombre": "Laptop HP 240 G8 Core i5 1135G7 16GB M.2 256GB SSD W11H 14 HP 79L97LT-V4",
        "procesador": "Intel Core i5-8350U",
        "grafica": "Intel Graphics",
        "memoriaRam": "16GB",
        "almacenamiento": "256GB HDD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 10499,
        "imagen": "1697655440988rku31f46gk8.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 4,
        "marcasLaptopId": 1,
        "tiendaId": 3
      },
      {
    
        "nombre": "HP Stream 11-ak1035nr 11.6\", Intel Atom™ x5 E8000, Ram 4GB, 32GB eMMC, Intel HD Graphics 400, W10 Home, Cámara Web Integrada, Blanco HP 11-ak1035nr",
        "procesador": "Intel Atom x5-E8000",
        "grafica": "Intel Graphics",
        "memoriaRam": "4GB",
        "almacenamiento": "256GB HDD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 6599,
        "imagen": "1697655637601jsbs13247v.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 1,
        "marcasLaptopId": 1,
        "tiendaId": 3
      },
      {
    
        "nombre": "Laptop HP Pavilion 14-dy2005 Intel Core i5 8GB RAM 256GB SSD",
        "procesador": "Intel Core i5-8200Y",
        "grafica": "Intel Graphics",
        "memoriaRam": "8GB",
        "almacenamiento": "256GB HDD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 19999,
        "imagen": "1697655698525celt4qknbtg.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 4,
        "marcasLaptopId": 1,
        "tiendaId": 3
      },
      {
        "nombre": "Laptop HP Omen Gaming 16-c0502la AMD Ryzen 7 8GB RAM GPU NVIDIA GeForce RTX 3050 512GB SSD",
        "procesador": "AMD Ryzen 7 PRO 5850U",
        "grafica": "Nvidia RTX 3050 (6GB)",
        "memoriaRam": "8GB",
        "almacenamiento": "512GB SSD + 1TB HDD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 20499,
        "imagen": "1697655778984mgbgdj4otl.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 4,
        "marcasLaptopId": 1,
        "tiendaId": 3
      },
      {
        "nombre": "Laptop Huawei Matebook D15 15.6'' Windows 11 Home Intel Core i5 8 GB RAM 512 GB SSD Plata",
        "procesador": "Intel Core i5-13450HX",
        "grafica": "Intel UHD Graphics",
        "memoriaRam": "8GB",
        "almacenamiento": "512GB SSD + 1TB HDD",
        "bateria": 8000,
        "interfaz": "PCI-express",
        "precio": 15999,
        "imagen": "16977470495252lg8132bda.jpg",
        "oferta": false,
        "descuento": 0,
        "sistemaOperativoId": 4,
        "marcasLaptopId": 10,
        "tiendaId": 1
      }


    ]
    
export default laptops;